import "./globals.css";
import NavBar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className="">
        <NavBar />
      </body>
      <main>{children}</main>
    </html>
  );
}
